@startuml

title Diagramme de Cas d'Utilisation

actor Locataire
actor Propriétaire

rectangle Système {
  usecase "S'inscrire" as UC1
  usecase "Créer propriété" as UC2
  usecase "Créer contrat" as UC3
  usecase "Signer contrat" as UC4
  usecase "Payer loyer" as UC5
  usecase "Déposer litige" as UC6
}

Locataire --> UC1
Locataire --> UC4
Locataire --> UC5
Locataire --> UC6

Propriétaire --> UC1
Propriétaire --> UC2
Propriétaire --> UC3
Propriétaire --> UC4
Propriétaire --> UC6

@enduml
